{
 "title": "flink-sql-demo",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Orders Created(second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(kafka_server:BrokerTopicMetrics_MessagesInPerSec_Count{topic=\"orders\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Flow Processed(second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(kafka_server:BrokerTopicMetrics_MessagesInPerSec_Count{topic=\"flow_orders\"}[$__rate_interval])"
    }
   ]
  },
  { "title": "Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Structured Processed(second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(kafka_server:BrokerTopicMetrics_MessagesInPerSec_Count{topic=\"structured_orders\"}[$__rate_interval])"
    }
   ]
  }
 ]
}